---

- tags:
  - config
  block:
    - name: Replace Prometheus main configuration file
      include_role:
        name: common
        tasks_from: linux/replace_prometheus_config.yml
  become: yes
  become_user: prometheus
